

switch:
- platform: custom
  lambda: |-
    auto lvAkey = new LivoloSwitch(5,17689,08);
    auto lvBkey = new LivoloSwitch(5,17689,16);
    auto lvCkey = new LivoloSwitch(5,17689,56);
    auto lvDkey = new LivoloSwitch(5,17689,42);
    App.register_component(lvAkey);
    App.register_component(lvBkey);
    App.register_component(lvCkey);
    App.register_component(lvDkey);
    return {lvAkey,lvBkey,lvCkey,lvDkey};
  switches:
    - name: "Livolo key A"
      id: livoloAkey
    - name: "Livolo key B"
      id: livoloBkey
    - name: "Livolo key C"
      id: livoloCkey
    - name: "Livolo key D"
      id: livoloDkey
